/opt/mssql-tools/bin/sqlcmd -S "127.0.0.1,1401" -d "master" -U SA -P "Passw0rd" -Q "
CREATE DATABASE TAG_DB;
GO
ALTER DATABASE TAG_DB SET RECOVERY FULL;
GO
BACKUP DATABASE TAG_DB TO DISK = 'NUL:';
GO
BACKUP LOG TAG_DB TO  DISK = 'NUL:';
GO
ALTER AVAILABILITY GROUP [AG] ADD DATABASE [TAG_DB];
GO"
