/opt/mssql-tools/bin/sqlcmd -S "127.0.0.1,1402" -d "master" -U SA -P "Passw0rd" -Q "
ALTER AVAILABILITY GROUP [AG] JOIN WITH (CLUSTER_TYPE = NONE);
GO
ALTER AVAILABILITY GROUP [AG] GRANT CREATE ANY DATABASE;
GO"

/opt/mssql-tools/bin/sqlcmd -S "127.0.0.1,1403" -d "master" -U SA -P "Passw0rd" -Q "
ALTER AVAILABILITY GROUP [AG] JOIN WITH (CLUSTER_TYPE = NONE);
GO
ALTER AVAILABILITY GROUP [AG] GRANT CREATE ANY DATABASE;
GO"
